title:       Daniel Martins
tagline:     Software Engineer
description:

# Comment out url when working locally to resolve base urls correctly
url: https://danielfm.me

# Google analytics tracking
analytics:
  code: UA-761701-11
  domain: danielfm.me

# Owner/author information
owner:
  name:           Daniel Martins
  avatar:         http://www.gravatar.com/avatar/fddde9212fa2082e7c5eb27b069567d9.png?s=200
  bio:            Software engineer @ Descomplica
  email:          daniel.tritone@gmail.com
  disqus:         danielfm
  twitter:        danielfmt
  github:         danielfm

# Links to include in top navigation
# For external links add external: true
links:
  - title: Portfolio
    url: /portfolio.html
  - title: Sounds
    url: https://soundcloud.com/danielfm
    external: true
  - title: About
    url: /about.html

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
markdown:    kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /posts/:title.html

sass:
  sass_dir: assets/css
  style: :compressed

gems:
- emoji_for_jekyll

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
